#!/bin/bash

JAVA_HOME=/usr/lib/jvm/default-java/
SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"

if [ -d $(dirname $0)/sbt-boot ]; then
  SBT_BOOT="-Dsbt.boot.directory=$(dirname $0)/sbt-boot/"
else
  SBT_BOOT=""
fi

if [ -d $(dirname $0)/ivy-cache ]; then
  IVY_CACHE="-Dsbt.ivy.home=$(dirname $0)/ivy-cache/"
else
  IVY_CACHE=""
fi

java $IVY_CACHE $SBT_BOOT $SBT_OPTS -jar `dirname $0`/sbt-launch.jar "$@"
