# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'ubuntu12.04'

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = 'http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box'

  # Hostname
  config.vm.host_name = 'juicer-debian-buildvm'

  # Memory
  config.vm.customize ["modifyvm", :id, '--memory', 2048]

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :hostonly, '192.168.33.30'

  config.vm.forward_port 80, 8111

  # Shared folder
  config.vm.share_folder 'workspace', '/mnt/hgfs/workspace', '.'

  # Provision
  config.vm.provision :shell, :inline => <<-eos
    apt-get upgrade
    apt-get update
  eos

end
